export {default as Navbar} from "./Navbar.jsx"
export {default as Expertise} from "./Expertise"
export {default as ProjectsList} from "./ProjectsList.jsx"
export {default as Testimonials} from "./Testimonials"
export {default as Contact} from "./Contact.jsx"